name: finance_dashboard
description: A modern finance dashboard built with Flutter.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # UI / Fonts
  google_fonts: ^6.1.0

  # Charts
  fl_chart: ^0.69.0

  # Local storage
  shared_preferences: ^2.2.2

  # CSV Export + Share
  share_plus: ^7.2.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
